/*
	STM32U3 series enhanced defs
	gbm 09'2025

	To be included instead of the original stm32U3xx.h.
*/

#ifndef __STM32U3YY_H
#define __STM32U3YY_H

#include <stdbool.h>
#include "stm32u3xx.h"
#include "stm32util.h"

#ifndef FLASH_PAGE_SIZE
#define FLASH_PAGE_SIZE	0x1000
#endif
#define	FLASH_FKEY1	0x45670123
#define	FLASH_FKEY2	0xCDEF89AB

// Vcore range 1 required for 96 MHz opeeration

// STM32H5x register/bit defs not present in stm32h5xx.h file
#define GPIO_OSPEEDR_LO	0	// 16 MHz
#define GPIO_OSPEEDR_MED	1u		// 40 MHz
#define GPIO_OSPEEDR_HI	2u		// 80 MHz
#define GPIO_OSPEEDR_VHI	3u	// 80 MHz, same as HI

enum afn_ {AFN_SYS, AFN_TIM1_2, AFN_LPTIM1_TIM3, AFN_LPTIM2,
	AFN_USART1_2, AFN_SPI1, AFN_SPI2, AFN_SPI23_UART,
	AFN_I2C2, AFN_USART23, AFN_USB, AFN_I2C1,
	AFN_COMP, AFN_USART23x, AFN_TIM123, AFN_EVT};

#define	RCC_PLLxCFGR_PLLxSRC_HSI	RCC_PLL1CFGR_PLL1SRC_0
#define	RCC_PLLxCFGR_PLLxSRC_HSE	RCC_PLL1CFGR_PLL1SRC

#define RCC_CFGR1_SW_PLL1	RCC_CFGR1_SW

#define IOENR	AHB2ENR1	// IO port enable register alias

#define GPIOIDX(p)	(((uint8_t *)(p) - (uint8_t *)GPIOA) / ((uint8_t *)GPIOB - (uint8_t *)GPIOA))
#define RCC_IOENR_GPIOEN(p) ( (RCC_AHB2ENR1_GPIOAEN) << GPIOIDX(p) )

#define PWR_CR_PLSV(a)	(((a) & 7) << 5)     /*!< Bit 0 */

// Calibration values stored in ROM
#define VREFINT_mV	3000u
#define VREFINT_CAL	(*(const uint16_t *)0x0bfa07a5)	// @ 3.0 V

#define T_CAL1	30
#define T_CAL2	110
#define TS_CAL1	(*(const uint16_t *)0x0bfa0710)	// @ 3.0 V, 30 deg C
#define TS_CAL2	(*(const uint16_t *)0x0bfa0742)	// @ 3.0 V, 110 deg C

// ADC channels with internal connections
#define ADCH_VREFINT	0u
#define ADCH_DAC1OUT1	14u
#define ADCH_DAC1OUT2	15u
#define ADCH_VBAT4	16u
#define ADCH_VSENSE	17u
#define ADCH_VDDCORE	18u

#define	ADC_SMPT_1_5	0u
#define	ADC_SMPT_2_5	1u
#define	ADC_SMPT_6_5	2u
#define	ADC_SMPT_11_5	3u
#define	ADC_SMPT_23_5	4u
#define	ADC_SMPT_46_5	5u
#define	ADC_SMPT_246_5	6u
#define	ADC_SMPT_1499_5	7u

#define ADC_CCR_PRESC_DIV2	1u
#define ADC_CCR_PRESC_DIV4	2u
#define ADC_CCR_PRESC_DIV6	3u
#define ADC_CCR_PRESC_DIV8	4u
#define ADC_CCR_PRESC_DIV10	5u
#define ADC_CCR_PRESC_DIV12	6u
#define ADC_CCR_PRESC_DIV16	7u
#define ADC_CCR_PRESC_DIV32	8u
#define ADC_CCR_PRESC_DIV64	9u

// The default clock after reset is MSIS @ 12 MHz
#ifndef HSI_VALUE
#define HSI_VALUE	16000000u
#endif

enum gpdma_rq_ {DMARQ_ADC1, DMARQ_ADC2,
	DMARQ_DAC1CH1, DMARQ_DAC1CH2, DMARQ_TIM6_UPD, DMARQ_TIM7_UPD,
	DMARQ_SPI1_RX = 6, DMARQ_SPI1_TX, DMARQ_SPI2_RX, DMARQ_SPI2_TX, DMARQ_SPI3_RX, DMARQ_SPI3_TX,
	DMARQ_I2C1_RX, DMARQ_I2C1_TX, DMARQ_I2C1_EVC, DMARQ_I2C2_RX, DMARQ_I2C2_TX, DMARQ_I2C2_EVC, DMARQ_I2C3_RX, DMARQ_I2C3_TX, DMARQ_I2C3_EVC,
	DMARQ_USART1_RX = 24, DMARQ_USART1_TX, DMARQ_USART2_RX, DMARQ_USART2_TX, DMARQ_USART3_RX, DMARQ_USART3_TX,
	DMARQ_UART4_RX, DMARQ_UART4_TX, DMARQ_UART5_RX, DMARQ_UART5_TX,
	DMARQ_LPUART1_RX = 34, DMARQ_LPUART1_TX,
	DMARQ_TIM1_CC1 = 42, DMARQ_TIM1_CC2, DMARQ_TIM1_CC3, DMARQ_TIM1_CC4,
	DMARQ_TIM1_UPD, DMARQ_TIM1_TRG, DMARQ_TIM1_COM,
	
	DMARQ_TIM2_CC1 = 56, DMARQ_TIM2_CC2, DMARQ_TIM2_CC3, DMARQ_TIM2_CC4, DMARQ_TIM2_UPD,
	DMARQ_TIM3_CC1 = 61, DMARQ_TIM3_CC2, DMARQ_TIM3_CC3, DMARQ_TIM3_CC4, DMARQ_TIM3_UPD, DMARQ_TIM3_TRG,
	DMARQ_TIM4_CC1 = 67, DMARQ_TIM4_CC2, DMARQ_TIM4_CC3, DMARQ_TIM4_CC4, DMARQ_TIM4_UPD,
	
	DMARQ_TIM15_CC1 = 78, DMARQ_TIM15_UPD, DMARQ_TIM15_TRG,
	DMARQ_TIM16_CC1, DMARQ_TIM16_UPD, DMARQ_TIM16_TRG,
	DMARQ_TIM17_CC1, DMARQ_TIM17_UPD,

	DMARQ_LPTIM1_IC1 = 105, DMARQ_LPTIM1_IC2, DMARQ_LPTIM1_UE,
	DMARQ_LPTIM2_IC1, DMARQ_LPTIM2_IC2, DMARQ_LPTIM2_UE,
	DMARQ_LPTIM3_IC1, DMARQ_LPTIM3_IC2, DMARQ_LPTIM3_UE,
};
enum gpdma_trig_ {GPDMA_TRIG_EXTI0, GPDMA_TRIG_EXTI1, GPDMA_TRIG_EXTI2, GPDMA_TRIG_EXTI3,
	GPDMA_TRIG_EXTI4, GPDMA_TRIG_EXTI5, GPDMA_TRIG_EXTI6, GPDMA_TRIG_EXTI7,
};

#define	DMA_CFCR_ALLF	(DMA_CFCR_TOF | DMA_CFCR_SUSPF | DMA_CFCR_USEF | DMA_CFCR_ULEF | DMA_CFCR_DTEF | DMA_CFCR_HTF | DMA_CFCR_TCF)

#define LPTIM_PRESC_64	6u
#define LPTIM_PRESC_128	7u

#include "stm32yyyy.h"	// add defs common to STM32 family

#endif
